# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT120Rc < Formula
  desc ""
  homepage ""
  version "1.2.0-devenv.2+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.2+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "a49ecf980b7ec186097b9a8b1eef997e6c954b1ad79282d22a5e785993b3ccac"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.2+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "bdc676fc4ab70dc0ebfcb4d5a519ea97e82f3c17049605a3f966ecd42e45e8cb"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.2+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "e19442850f4fb7f7b36af5a89916270be67382e06e554a7533252f48156c9af9"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.2+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "3bf642a7153c7543120369d3ec152308950cc79eac32e59f7f19db632936a4b5"

      def install
        bin.install "devenv"
      end
    end
  end
end
