# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT120Rc < Formula
  desc ""
  homepage ""
  version "1.2.0-devenv.0+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.0+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "12f2dc8f00b27135d5a01a187d6e1ef1a5da9fe20e37ae369d793978a64cba65"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.0+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "bf05a11f1798d8bd0312e00ea458f168ad17a16df433afbf6bc7943c8ce21dfa"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.0+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "6054f225d703ce6b939d36dfd812014b920752aa319248986caf44b713e74b34"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.0+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "f7342938f71e778191ae2204b386d8ca0c7661594706d4f8d545082e9ea89612"

      def install
        bin.install "devenv"
      end
    end
  end
end
