# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT100Devenv0 < Formula
  desc ""
  homepage ""
  version "1.0.0-devenv.0+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.0+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "3dea8746d51b7aa529e5e57dc6934966f973d01a2eef36ec50a624626398525c"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.0+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "b8d4ea725cb1419db6b95b26c588b9d9108a462465a974e0f0f0842f4fa5bcfb"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.0+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "f8922ecd4d1e6fa6b2b66e35f22246df17443554e3025fb4eaef415ec7c865bc"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.0+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "f938598d55c972ad6b8bad8f3174321bd554d5af16401157c5f7303931c96434"

      def install
        bin.install "devenv"
      end
    end
  end
end
