# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT120Devenv3 < Formula
  desc ""
  homepage ""
  version "1.2.0-devenv.3+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.3+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "ece76b5e168fe422d7e8fa4d73f0263340ffee03ba1fe4630817bb61e4d5214a"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.3+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "3d200306caf19264155b75c4736eeeab5e6496f5af121819ace0cfaf6e4b9040"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.3+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "7a343c0e110bead7d45cc8cda994e5a403aa55342205c23ae93dacfa43cb0c67"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.3+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "3b3e9a8305912fdd5a7392025301e773dbd6d0eee9162b5a09895ce8fccbe67f"

      def install
        bin.install "devenv"
      end
    end
  end
end
