# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT020Rc < Formula
  desc ""
  homepage ""
  version "0.2.0-devenv.2+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v0.2.0-devenv.2+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "e1a04e5cc0dfe436d972929d5866165d9588f895c3296ec0243cb3084738e745"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v0.2.0-devenv.2+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "d12a08a26050c4a2c398c4bb1307d110c077452e4ccbeb54e6bacf535746fe99"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v0.2.0-devenv.2+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "fc91e03dc45c070025a402848b8bc572e09aecb6ce4a55641bb18adf15ff2a58"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v0.2.0-devenv.2+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "521dc311600f3b96337c8c0046e5cbb46e16838ea1e79b585cffc83e2290099d"

      def install
        bin.install "devenv"
      end
    end
  end
end
