# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT120Rc < Formula
  desc ""
  homepage ""
  version "1.2.0-devenv.4+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.4+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "10efa999b9d82006d014e91bdf3d420d06fc4ecdcea5dc21a55f53c2993ea317"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.4+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "aff879aea1d12a9ff99b45202490fdc35592b9819d7be9617101a4e55cd09549"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.4+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "05b178b15a0e1110a47a3447e80cfea81869aad3791e8c4365d6e67d07bedeeb"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.4+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "ab6fde9f84b48daeafc3f6d7877e423babfd1d00fd3799848d5179e2a6a182f9"

      def install
        bin.install "devenv"
      end
    end
  end
end
