# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT120Devenv1 < Formula
  desc ""
  homepage ""
  version "1.2.0-devenv.1+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.1+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "2e3fab35b493f2c6cbccb60ac09b471a60adfa3f150f4d0dd0e7f4a98477d76f"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.1+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "1684a7d42521e504738012c43223d25fbd6f3e1efbf7a2a9abef2a86a2512091"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.1+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "89c135592b8dc1a0717b2b22cd0a704e5d3a4d8ad783e78301540041caed5ca8"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.0-devenv.1+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "8f7a894daed939265d47092215f012ede835b99cc17aca417442eae514a1c6c2"

      def install
        bin.install "devenv"
      end
    end
  end
end
