# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT100Devenv1 < Formula
  desc ""
  homepage ""
  version "1.0.0-devenv.1+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.1+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "547aa248ae0100ff0c96d12b178524fc53ebbc17a0f0257a5d8e300846760955"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.1+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "495f97da5e3dcf882d8479b3be9134365e845f273b1ba46d3803ccf8ef4d7d00"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.1+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "5e22f8f03ae0c46eb54a8819b77eb5f0e78389001efbd6792ba4153ff10ff1a8"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.1+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "0a1f5d47820af75ff2f1bb3768c638166821d6d878d4d31095e158b10e57a8cb"

      def install
        bin.install "devenv"
      end
    end
  end
end
