# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT121Rc < Formula
  desc ""
  homepage ""
  version "1.2.1-devenv.0+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.2.1-devenv.0+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "378c9c0f8769296354c8ad3064e71aa2c23f312bf3588b7a607b39d87755e76d"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.1-devenv.0+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "729befbed27438787edce9c5063a780ed08c6d51179b83ea370f3f9407871321"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.2.1-devenv.0+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "308e40b334e8cd6cc3eee8bfd523d4590f5026c488a4acb095e03cff0e853ce4"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.2.1-devenv.0+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "ce8a3a0319b8d206545f90a6e00a0ba48bbcd38a9e82a208261029e5cae342e2"

      def install
        bin.install "devenv"
      end
    end
  end
end
