# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT100Rc < Formula
  desc ""
  homepage ""
  version "1.0.0-devenv.2+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.2+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "fe30c80eb7d90b449315a33cf1ff221c129e3e809c947d5365843baacba6a619"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.2+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "bea99ec61dde3189f6772a3aec42740747aa06590fbea60819252faf327a84d4"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.2+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "fa5783996949ca5ea19eec29f63ae08c890934eebf5ebeffce084c0c564493e9"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.0.0-devenv.2+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "6041af1ccab00c0b0b47547758c00614c4c4b34cd4722a6a60bad14a0ec9b29f"

      def install
        bin.install "devenv"
      end
    end
  end
end
