# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT110Rc < Formula
  desc ""
  homepage ""
  version "1.1.0-devenv.2+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.2+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "b7b85a6684424a8f6b8660233fb90a475a42f235e5318b9f740b72f74b578348"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.2+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "35b301a54e058eb5bf86aa1bb6f9a48558e0ebba97b93c9e9dae236c534169b7"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.2+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "6960daf0148ecdf6d02ddb0845ea3e085048ef2a5b08ee9533f3e745ac2fb4b3"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.2+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "f03c47e494706bb9cc6d0f3bc8a9805364c7929ef1c1979dcb048cc8d88cd7e5"

      def install
        bin.install "devenv"
      end
    end
  end
end
