# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT110Devenv3 < Formula
  desc ""
  homepage ""
  version "1.1.0-devenv.3+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.3+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "61e596a596d32dc8c371e0f82f52a65b7546374b399b6dec0d45ad71893c7c70"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.3+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "6598edc609b0d80bfd57875db757ca643a56f1ab39ad6f4a1c92285befd0f40f"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.3+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "2660daf62020ba284762b0df5bbd2a520f90396e6727fb1e2ebca684e1b11d51"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.3+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "579e21251de68664a151234a0a2e792188598c28d1d2014bcd5a4f7b73991ad2"

      def install
        bin.install "devenv"
      end
    end
  end
end
