# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DevenvAT110Devenv0 < Formula
  desc ""
  homepage ""
  version "1.1.0-devenv.0+goreleaser"

  depends_on "direnv"
  depends_on "eget"
  depends_on "go-task"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.0+goreleaser/devenv_darwin_arm64.tar.gz"
      sha256 "a9faea2e40d275018a4c04e3ce35ea3c574ac6d31b0da4638dccb48cd8495534"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.0+goreleaser/devenv_darwin_amd64.tar.gz"
      sha256 "7c3d66402eea2b6d1f742f05a20588d2aadb23a29d6e78345567d1fa5bb63389"

      def install
        bin.install "devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.0+goreleaser/devenv_linux_arm64.tar.gz"
      sha256 "d5d4be8dbd72ee825f24a87397ab1457c275990a11125fbf1d8881939a50853c"

      def install
        bin.install "devenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/metafeather/tools/releases/download/v1.1.0-devenv.0+goreleaser/devenv_linux_amd64.tar.gz"
      sha256 "c1637d76c3168f8ec60498b34aa2b3c7065c1be9f884327d1db486ea6b05fe25"

      def install
        bin.install "devenv"
      end
    end
  end
end
